### ISSUE TITLE
ownership transfer

### ISSUE THREAD

**Issue by blackPeanut** [ianlin/react-native-carrier-info#2]
Hi! I want to maintain this library. Can we discuss ownership transfer?
Can't find your contact, my email is daniel@galt.hk
Thanks :)

**Comment by ghost** [comment]
Hi, Yeah no problem. Let me know the username for github and npm where you want the repo to be transferred

**Comment by ianlin** [comment]
Hey guys any news on this? Cheers!

**Comment by srounce** [comment]
Hi, just added proper promise rejection to @ianlin's branch, not sure where to send the PR as there is no maintainer. Can we get an update on this?

**Comment by ghost** [comment]
I don't have any time to maintain this report, as stated in the readme.

More than happy to transfer the repo to someone who is able to maintain it

**Comment by ianlin** [comment]
Thanks, happy to maintain it.

GitHub: ianlin
Npm: ianyuhsunlin

**Comment by ghost** [comment]
@ianlin Have added you as owner on the npm package, can't transfer the repo as it says one already exists with that name under your account

**Comment by ianlin** [comment]
Oh ok maybe it's because I forked your repo, have renamed it so you can try
again, cheers!

**Comment by ghost** [comment]
just tried again and got the following message:

ianlin already has a repository in the anarchicknight/react-native-carrier-info network

**Comment by ianlin** [comment]
Just check GitHub FAQ it says the new owner cannot have a same repo name or
a fork so I just deleted the forked repo as I've got the local copy. Maybe
this time it would success. Ta!

**Comment by ghost** [comment]
that should now have been initiated

**Comment by ianlin** [comment]
Done! Thanks mate!
